# Generated by Django 3.0.7 on 2020-07-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coursemodel',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('Course_name', models.CharField(max_length=50, unique=True)),
                ('Faculty', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Fee', models.FloatField()),
            ],
        ),
    ]
