# Generated by Django 3.0.7 on 2020-07-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourse', '0002_coursemodel_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='Duration',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
