# Generated by Django 3.0.7 on 2020-07-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourse', '0004_auto_20200709_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='Duration',
            field=models.CharField(max_length=30),
        ),
    ]
