# Generated by Django 3.0.7 on 2020-07-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourse', '0005_auto_20200709_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursetable',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
                ('Faculty', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Fee', models.IntegerField()),
                ('Duration', models.CharField(max_length=50)),
            ],
        ),
    ]
