# Generated by Django 3.0.7 on 2020-07-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourse', '0006_coursetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='centermodel',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('fee', models.TimeField()),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='coursemodel',
        ),
        migrations.DeleteModel(
            name='Coursetable',
        ),
    ]
