# Generated by Django 3.0.7 on 2020-07-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourse', '0007_auto_20200711_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centermodel',
            name='time',
            field=models.CharField(max_length=25),
        ),
    ]
