# Generated by Django 3.0.7 on 2020-07-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourse', '0008_auto_20200711_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centermodel',
            name='fee',
            field=models.IntegerField(),
        ),
    ]
