# Generated by Django 3.0.7 on 2020-07-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourse', '0010_auto_20200714_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentregistration',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Contactno', models.IntegerField(unique=True)),
                ('Email', models.EmailField(max_length=60, unique=True)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
